### ISSUE TITLE
The resource `deBarbaroCry` is not accessible

### ISSUE THREAD

**Issue by jogloran** [AgnesMayYao/Infant-Crying-Detection#1]
The link to the resource in the README file (https://homebank.talkbank.org/access/Secure/deBarbaroCry-protect/deBarbaroCry.html) goes to a 404.

**Comment by AgnesMayYao** [comment]
Hi 

Can you try this link: https://homebank.talkbank.org/access/Password/deBarbaroCry.html

We changed the access level from _limited_ to _members_, thus causing this issue. About homebank membership, check this link: https://homebank.talkbank.org/membership.html.

Thanks,
Xuewen

**Comment by mikebartorn** [comment]
Hi I would like to know if there is any documentation about the whole model

**Comment by mikebartorn** [comment]
And I want to know if the code of the preprocess file is the processing step of data preprocess in section 3.4 of the paper?
